# Generated by Django 5.2.7 on 2026-06-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitle')),
                ('header', models.CharField(max_length=200, verbose_name='Header')),
                ('paragraph', models.TextField(verbose_name='Paragraph')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me - Content',
                'verbose_name_plural': 'About Me - Content',
            },
        ),
        migrations.CreateModel(
            name='AboutMeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AboutMe/', verbose_name='Image')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me - Image',
                'verbose_name_plural': 'About Me - Images',
            },
        ),
        migrations.CreateModel(
            name='AboutMeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10, verbose_name='Value')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Me - Stat',
                'verbose_name_plural': 'About Me - Stats',
            },
        ),
    ]
